server:
  port: 8086
  servlet:
    context-path: /api/anti-fraud
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
management:
  server:
    port: 8186
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    properties:
      hibernate:
        default_schema: anti_fraud
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secretpassword
  liquibase:
    default-schema: anti_fraud
    change-log: db/changelog/db.changelog-master.yaml
    enabled: ${LIQUIBASE_ENABLED:true}
    drop-first: ${LIQUIBASE_DROP_FIRST:false}
  application:
    name: anti-fraud-app
